// File: /src/app/layout.tsx

import { ReactNode } from 'react';
import SessionLayout from '@/src/app/components/Provider/SessionLayout'; // Importing the client component

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SessionLayout>
          {children}
        </SessionLayout>
      </body>
    </html>
  );
}
